sudo: required 

services: 
    - docker

before_install:
    - docker build -f Dockerfile.dev -t testimage .

script: 
    - docker run -e CI=true testimage npm run test -- --coverage

deploy: 
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "dockerApp"
    env: "Dockerapp-env"
    bucket_name: "elasticbeanstalk-eu-west-2-21993671448"
    bucket_path: "dockerApp"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
    
        